export type LlcStatus = 'operating' | 'under_construction' | 'proposed' | 'approved' | 'cancelled';

export interface LlcEntry {
  llcName: string;
  company: string;
  confidence: string;
  state: string;
  location: string;
  project: string;
  lat: number;
  lng: number;
  status: LlcStatus;
  facilityType: string;
  incentivesKnown: boolean;
  incentiveAmount: number;
  ndaInvolved: boolean;
  sourceType: string;
  notes: string;
}

export interface CompanyProfile {
  name: string;
  slug: string;
  description: string;
  llcCount: number;
  llcs: LlcEntry[];
}

const googleLlcs: LlcEntry[] = [
  {
    llcName: 'Design LLC',
    company: 'Google',
    confidence: 'confirmed',
    state: 'DE/NV',
    location: 'Henderson, Nevada, USA',
    project: 'Henderson Data Center',
    lat: 36.0397,
    lng: -114.9817,
    status: 'operating',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 50000000,
    ndaInvolved: false,
    sourceType: 'news',
    notes: 'Wholly owned Google subsidiary; owns/builds facility while Google operates it',
  },
  {
    llcName: 'Design LLC',
    company: 'Google',
    confidence: 'confirmed',
    state: 'DE/NV',
    location: 'Sparks, Nevada, USA',
    project: 'Tahoe Reno Industrial Center Data Center',
    lat: 39.5349,
    lng: -119.7527,
    status: 'operating',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 50000000,
    ndaInvolved: false,
    sourceType: 'news',
    notes: 'Storey County facility under same Design LLC entity',
  },
  {
    llcName: 'Design LLC',
    company: 'Google',
    confidence: 'confirmed',
    state: 'DE/NV',
    location: 'The Dalles, Oregon, USA',
    project: 'The Dalles Data Center Expansion',
    lat: 45.5946,
    lng: -121.1787,
    status: 'under_construction',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 0,
    ndaInvolved: false,
    sourceType: 'news',
    notes: 'Expansion of existing Google The Dalles campus',
  },
  {
    llcName: 'Groot LLC',
    company: 'Google',
    confidence: 'confirmed',
    state: 'DE',
    location: 'West Memphis, Arkansas, USA',
    project: 'West Memphis Data Center Campus (Project Pyramid)',
    lat: 35.1465,
    lng: -90.1845,
    status: 'approved',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 50000000000,
    ndaInvolved: true,
    sourceType: 'news',
    notes: '$10B PILOT deal; up to $50B in personal property tax abatements',
  },
  {
    llcName: 'Spark Innovations LLC',
    company: 'Google',
    confidence: 'probable',
    state: 'DE',
    location: 'West Memphis, Arkansas, USA',
    project: 'West Memphis Data Center Proposal (Spark)',
    lat: 35.1465,
    lng: -90.1845,
    status: 'cancelled',
    facilityType: 'hyperscale data center',
    incentivesKnown: false,
    incentiveAmount: 0,
    ndaInvolved: true,
    sourceType: 'news',
    notes: 'Separate proposed campus; cancelled after community opposition',
  },
  {
    llcName: 'Spark Innovations LLC',
    company: 'Google',
    confidence: 'probable',
    state: 'DE',
    location: 'St. Charles, Missouri, USA',
    project: 'St. Charles Data Center Proposal',
    lat: 38.7881,
    lng: -90.4974,
    status: 'proposed',
    facilityType: 'hyperscale data center',
    incentivesKnown: false,
    incentiveAmount: 0,
    ndaInvolved: true,
    sourceType: 'news',
    notes: '$600M data center proposal under Project Shale umbrella',
  },
  {
    llcName: 'Montauk Innovations LLC',
    company: 'Google',
    confidence: 'confirmed',
    state: 'DE/OH',
    location: 'New Albany, Ohio, USA',
    project: 'New Albany Data Center Campus',
    lat: 40.0809,
    lng: -82.7913,
    status: 'operating',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 63000000,
    ndaInvolved: false,
    sourceType: 'sec_filing',
    notes: 'CRA tax incentives; 85 acres acquired for $63M',
  },
  {
    llcName: 'Montauk Innovations LLC',
    company: 'Google',
    confidence: 'confirmed',
    state: 'DE/OH',
    location: 'New Albany, Ohio, USA',
    project: 'New Albany Expansion Phases',
    lat: 40.0809,
    lng: -82.7913,
    status: 'under_construction',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 63000000,
    ndaInvolved: false,
    sourceType: 'sec_filing',
    notes: 'Expansion phases of existing New Albany campus',
  },
  {
    llcName: 'Sharka LLC',
    company: 'Google',
    confidence: 'confirmed',
    state: 'TX',
    location: 'Midlothian, Texas, USA',
    project: 'Midlothian Data Center Campus',
    lat: 32.4738,
    lng: -97.0003,
    status: 'operating',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 10000000,
    ndaInvolved: false,
    sourceType: 'news',
    notes: '$10M+ over 10-year tax abatement; Ellis County',
  },
  {
    llcName: 'Agate LLC',
    company: 'Google',
    confidence: 'confirmed',
    state: 'DE',
    location: 'Lincoln, Nebraska, USA',
    project: 'Lincoln Data Center Campus',
    lat: 40.8136,
    lng: -96.7026,
    status: 'under_construction',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 0,
    ndaInvolved: false,
    sourceType: 'news',
    notes: '$600M campus; 570+ acres of farmland acquired',
  },
  {
    llcName: 'Pearl Computing Malaysia Sdn Bhd',
    company: 'Google',
    confidence: 'probable',
    state: 'MY',
    location: 'Various (Elmina, Port Dickson, Eco Business Park V)',
    project: 'Malaysia Cloud Region and Data Center Sites',
    lat: 3.1390,
    lng: 101.6869,
    status: 'under_construction',
    facilityType: 'hyperscale data center',
    incentivesKnown: false,
    incentiveAmount: 0,
    ndaInvolved: false,
    sourceType: 'news',
    notes: 'Malaysian entity used for regional expansion',
  },
  {
    llcName: 'Questa LLC',
    company: 'Google',
    confidence: 'confirmed',
    state: 'DE',
    location: 'Council Bluffs, Iowa, USA',
    project: 'Council Bluffs Data Center',
    lat: 41.2619,
    lng: -95.8608,
    status: 'operating',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 1,
    ndaInvolved: false,
    sourceType: 'news',
    notes: 'City sold 850 acres for $1; development deal with Gable Corp',
  },
  {
    llcName: 'Gable Corp',
    company: 'Google',
    confidence: 'confirmed',
    state: 'DE',
    location: 'Council Bluffs, Iowa, USA',
    project: 'Council Bluffs Development Deal',
    lat: 41.2619,
    lng: -95.8608,
    status: 'operating',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 1,
    ndaInvolved: false,
    sourceType: 'news',
    notes: 'Partner entity to Questa LLC for Council Bluffs acquisition',
  },
  {
    llcName: 'Heaviside LLC',
    company: 'Google',
    confidence: 'confirmed',
    state: 'DE',
    location: 'Cedar Rapids, Iowa, USA',
    project: 'Big Cedar Data Center',
    lat: 42.0083,
    lng: -91.6441,
    status: 'operating',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 56000000,
    ndaInvolved: false,
    sourceType: 'news',
    notes: '$56M in tax breaks; 20-year 70% exemption',
  },
  {
    llcName: 'Magellan Enterprises LLC',
    company: 'Google',
    confidence: 'confirmed',
    state: 'OH',
    location: 'Columbus, Ohio, USA',
    project: 'Columbus Hartman Farm Data Center',
    lat: 40.0150,
    lng: -82.9988,
    status: 'operating',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 54300000,
    ndaInvolved: false,
    sourceType: 'news',
    notes: '$54.3M property tax abatement (100% 15-year CRA); $2.7M per job created',
  },
  {
    llcName: 'Tilted Gate LLC',
    company: 'Google',
    confidence: 'confirmed',
    state: 'DE/OH',
    location: 'Franklin Furnace, Ohio, USA',
    project: 'Scioto County Data Center',
    lat: 38.6434,
    lng: -82.8432,
    status: 'proposed',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 0,
    ndaInvolved: false,
    sourceType: 'news',
    notes: '75% property tax abatement; 15-year PILOT',
  },
  {
    llcName: 'Bistrozzi LLC',
    company: 'Google',
    confidence: 'confirmed',
    state: 'OH',
    location: 'Lima, Ohio, USA',
    project: 'Lima Area Data Center',
    lat: 40.7423,
    lng: -84.1052,
    status: 'proposed',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 0,
    ndaInvolved: false,
    sourceType: 'news',
    notes: 'Identity confirmed after public hearings',
  },
  {
    llcName: 'Fireball Group LLC',
    company: 'Google',
    confidence: 'confirmed',
    state: 'DE',
    location: 'Papillion, Nebraska, USA',
    project: 'Project Wizard Data Center',
    lat: 41.1544,
    lng: -96.0422,
    status: 'proposed',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 0,
    ndaInvolved: true,
    sourceType: 'news',
    notes: '$600M investment; Nebraska tax incentives',
  },
  {
    llcName: 'Hatchworks LLC',
    company: 'Google',
    confidence: 'confirmed',
    state: 'DE/IN',
    location: 'Fort Wayne, Indiana, USA',
    project: 'Project Zodiac Data Center',
    lat: 41.1306,
    lng: -85.1289,
    status: 'proposed',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 0,
    ndaInvolved: true,
    sourceType: 'news',
    notes: '50% tax abatement for 10 years; state sales tax exemption',
  },
  {
    llcName: 'Harmony Group LLC',
    company: 'Google',
    confidence: 'confirmed',
    state: 'DE',
    location: 'Hermantown, Minnesota, USA',
    project: 'Project Loon Data Center',
    lat: 46.8258,
    lng: -92.2321,
    status: 'proposed',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 0,
    ndaInvolved: true,
    sourceType: 'news',
    notes: 'MN data center tax law applied; Google required 22 separate NDAs',
  },
  {
    llcName: 'Shalerock LLC',
    company: 'Google',
    confidence: 'confirmed',
    state: 'DE',
    location: 'Kansas City, Missouri, USA',
    project: 'Project Shale Data Center',
    lat: 39.0997,
    lng: -94.5786,
    status: 'proposed',
    facilityType: 'hyperscale data center',
    incentivesKnown: false,
    incentiveAmount: 0,
    ndaInvolved: true,
    sourceType: 'news',
    notes: '$600M data center proposal',
  },
  {
    llcName: 'Alamo Mission LLC',
    company: 'Google',
    confidence: 'confirmed',
    state: 'DE/TX',
    location: 'Midlothian, Texas, USA',
    project: 'Midlothian Land Acquisition',
    lat: 32.4738,
    lng: -97.0003,
    status: 'operating',
    facilityType: 'land acquisition entity',
    incentivesKnown: false,
    incentiveAmount: 0,
    ndaInvolved: false,
    sourceType: 'news',
    notes: 'Land acquisition entity for 375-acre site',
  },
  {
    llcName: 'Jet Stream LLC',
    company: 'Google',
    confidence: 'confirmed',
    state: 'DE',
    location: 'Midlothian, Texas, USA',
    project: 'Midlothian Land Purchase',
    lat: 32.4738,
    lng: -97.0003,
    status: 'operating',
    facilityType: 'land acquisition entity',
    incentivesKnown: false,
    incentiveAmount: 0,
    ndaInvolved: false,
    sourceType: 'news',
    notes: 'Land purchase negotiation entity',
  },
  {
    llcName: 'Jasmine Development LLC',
    company: 'Google',
    confidence: 'confirmed',
    state: 'DE',
    location: 'Henderson, Nevada, USA',
    project: 'Henderson Land Acquisition',
    lat: 36.0397,
    lng: -114.9817,
    status: 'operating',
    facilityType: 'land acquisition entity',
    incentivesKnown: false,
    incentiveAmount: 19000000,
    ndaInvolved: true,
    sourceType: 'news',
    notes: 'Acquired 64 acres for $19M; NDA signed with city',
  },
  {
    llcName: 'Mallard LLC',
    company: 'Google',
    confidence: 'probable',
    state: 'DE',
    location: 'Ridgeville, South Carolina, USA',
    project: 'Project Dawson Data Center',
    lat: 33.0996,
    lng: -80.5662,
    status: 'proposed',
    facilityType: 'hyperscale data center',
    incentivesKnown: false,
    incentiveAmount: 0,
    ndaInvolved: true,
    sourceType: 'news',
    notes: 'Special 6¢/kWh electricity rate negotiated',
  },
  {
    llcName: 'Autumn Timber LLC',
    company: 'Google',
    confidence: 'probable',
    state: 'DE',
    location: 'Ridgeville, South Carolina, USA',
    project: 'Project Dawson Land Acquisition',
    lat: 33.0996,
    lng: -80.5662,
    status: 'proposed',
    facilityType: 'land acquisition entity',
    incentivesKnown: true,
    incentiveAmount: 5840000,
    ndaInvolved: true,
    sourceType: 'news',
    notes: 'Tax breaks; 268 acres acquired for $5.84M from county',
  },
  {
    llcName: 'White Rose Partners',
    company: 'Google',
    confidence: 'confirmed',
    state: 'OK',
    location: 'Sand Springs, Oklahoma, USA',
    project: 'Project Spring Data Center',
    lat: 36.1395,
    lng: -96.1081,
    status: 'proposed',
    facilityType: 'hyperscale data center',
    incentivesKnown: false,
    incentiveAmount: 0,
    ndaInvolved: true,
    sourceType: 'news',
    notes: 'Incentives under negotiation; 827 acres secured',
  },
];

const metaLlcs: LlcEntry[] = [
  {
    llcName: 'Siculus Inc.',
    company: 'Meta',
    confidence: 'confirmed',
    state: 'DE',
    location: 'Altoona, Iowa, USA',
    project: 'Project Catalyst Data Center',
    lat: 41.6491,
    lng: -93.4696,
    status: 'operating',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 18000000,
    ndaInvolved: false,
    sourceType: 'sec_filing',
    notes: '$18M in state tax credits; TIF; discounted water',
  },
  {
    llcName: 'Greater Kudu LLC',
    company: 'Meta',
    confidence: 'confirmed',
    state: 'DE',
    location: 'Los Lunas, New Mexico, USA',
    project: 'Project Discus Data Center',
    lat: 34.8070,
    lng: -106.7330,
    status: 'operating',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 30000000000,
    ndaInvolved: false,
    sourceType: 'sec_filing',
    notes: 'Up to $30B in IRBs; 30-year property tax exemption',
  },
  {
    llcName: 'Scout Development LLC',
    company: 'Meta',
    confidence: 'confirmed',
    state: 'DE',
    location: 'Henrico County, Virginia, USA',
    project: 'Project Echo Data Center',
    lat: 37.5538,
    lng: -77.4603,
    status: 'operating',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 0,
    ndaInvolved: false,
    sourceType: 'sec_filing',
    notes: 'County cut data center tax rate by 88%',
  },
  {
    llcName: 'Sidecat LLC',
    company: 'Meta',
    confidence: 'confirmed',
    state: 'DE',
    location: 'New Albany, Ohio, USA',
    project: 'Project Prometheus Data Center',
    lat: 40.0809,
    lng: -82.7913,
    status: 'operating',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 37000000,
    ndaInvolved: false,
    sourceType: 'sec_filing',
    notes: '$37M+ in state tax incentives; 15-year property tax exemption',
  },
  {
    llcName: 'Morning Hornet LLC',
    company: 'Meta',
    confidence: 'confirmed',
    state: 'DE',
    location: 'Newton County, Georgia, USA',
    project: 'Newton County Data Center',
    lat: 33.5518,
    lng: -83.8135,
    status: 'operating',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 42000000000,
    ndaInvolved: false,
    sourceType: 'sec_filing',
    notes: '$42B in phantom bonds from JDA; PILOT payments',
  },
  {
    llcName: 'Raven Northbrook LLC',
    company: 'Meta',
    confidence: 'confirmed',
    state: 'DE',
    location: 'Papillion, Nebraska, USA',
    project: 'Papillion Data Center',
    lat: 41.1544,
    lng: -96.0422,
    status: 'operating',
    facilityType: 'hyperscale data center',
    incentivesKnown: false,
    incentiveAmount: 0,
    ndaInvolved: false,
    sourceType: 'sec_filing',
    notes: 'Mixed-use development agreement',
  },
  {
    llcName: 'Starbelt LLC',
    company: 'Meta',
    confidence: 'confirmed',
    state: 'DE',
    location: 'Huntsville, Alabama, USA',
    project: 'Huntsville Data Center',
    lat: 34.7304,
    lng: -86.5861,
    status: 'operating',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 0,
    ndaInvolved: false,
    sourceType: 'sec_filing',
    notes: '340 acres for $8.5M; $750M investment',
  },
  {
    llcName: 'Woolhawk LLC',
    company: 'Meta',
    confidence: 'confirmed',
    state: 'DE',
    location: 'Gallatin, Tennessee, USA',
    project: 'Project Woolhawk Data Center',
    lat: 36.3884,
    lng: -86.4467,
    status: 'operating',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 0,
    ndaInvolved: true,
    sourceType: 'sec_filing',
    notes: '809 acres for ~$20M; $1.5B investment',
  },
  {
    llcName: 'Redale LLC',
    company: 'Meta',
    confidence: 'confirmed',
    state: 'DE',
    location: 'Mesa, Arizona, USA',
    project: 'Mesa Data Center',
    lat: 33.4152,
    lng: -111.8315,
    status: 'operating',
    facilityType: 'hyperscale data center',
    incentivesKnown: false,
    incentiveAmount: 123200000,
    ndaInvolved: false,
    sourceType: 'sec_filing',
    notes: '396 acres for $123.2M; no typical tax sweeteners',
  },
  {
    llcName: 'Vitesse LLC',
    company: 'Meta',
    confidence: 'confirmed',
    state: 'DE',
    location: 'Prineville, Oregon, USA',
    project: 'Prineville Data Center',
    lat: 44.2998,
    lng: -120.8340,
    status: 'operating',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 0,
    ndaInvolved: false,
    sourceType: 'sec_filing',
    notes: 'Oregon enterprise zone tax exemptions',
  },
  {
    llcName: 'Winner LLC',
    company: 'Meta',
    confidence: 'confirmed',
    state: 'DE',
    location: 'Fort Worth, Texas, USA',
    project: 'Fort Worth Data Center',
    lat: 32.7555,
    lng: -97.3308,
    status: 'operating',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 147000000,
    ndaInvolved: false,
    sourceType: 'sec_filing',
    notes: 'Up to $147M in incentives; 10-year county abatement',
  },
  {
    llcName: 'Velvet Tech Services LLC',
    company: 'Meta',
    confidence: 'confirmed',
    state: 'DE',
    location: 'Kansas City, Missouri, USA',
    project: 'Project Velvet Data Center',
    lat: 39.0997,
    lng: -94.5786,
    status: 'operating',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 8200000000,
    ndaInvolved: false,
    sourceType: 'sec_filing',
    notes: 'Up to $8.2B in city tax incentives',
  },
  {
    llcName: 'Goldframe LLC',
    company: 'Meta',
    confidence: 'confirmed',
    state: 'DE',
    location: 'DeKalb, Illinois, USA',
    project: 'DeKalb Data Center',
    lat: 41.9294,
    lng: -88.7501,
    status: 'operating',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 80000000,
    ndaInvolved: false,
    sourceType: 'sec_filing',
    notes: '$80M in tax exemptions; largest in IL history',
  },
  {
    llcName: 'Jimnist LLC',
    company: 'Meta',
    confidence: 'confirmed',
    state: 'DE',
    location: 'Rosemount, Minnesota, USA',
    project: 'Project Bigfoot Data Center',
    lat: 44.7419,
    lng: -93.1163,
    status: 'proposed',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 0,
    ndaInvolved: true,
    sourceType: 'sec_filing',
    notes: '280 acres for ~$40M; $800M+ investment',
  },
  {
    llcName: 'Goat Systems LLC',
    company: 'Meta',
    confidence: 'confirmed',
    state: 'DE',
    location: 'Cheyenne, Wyoming, USA',
    project: 'Project Cosmo Data Center',
    lat: 41.1400,
    lng: -104.8202,
    status: 'proposed',
    facilityType: 'hyperscale data center',
    incentivesKnown: false,
    incentiveAmount: 0,
    ndaInvolved: false,
    sourceType: 'sec_filing',
    notes: '945-acre site; incentive details undisclosed',
  },
  {
    llcName: 'Wurldwide LLC',
    company: 'Meta',
    confidence: 'confirmed',
    state: 'DE',
    location: 'El Paso, Texas, USA',
    project: 'El Paso Data Center',
    lat: 31.7619,
    lng: -106.4850,
    status: 'proposed',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 8570000,
    ndaInvolved: false,
    sourceType: 'sec_filing',
    notes: '1083 acres for $8.57M from city/county',
  },
  {
    llcName: 'Laidley LLC',
    company: 'Meta',
    confidence: 'probable',
    state: 'DE',
    location: 'Richland Parish, Louisiana, USA',
    project: 'Project Sucre Data Center',
    lat: 32.2907,
    lng: -91.7457,
    status: 'proposed',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 0,
    ndaInvolved: false,
    sourceType: 'news',
    notes: 'Special sales tax exemption legislation; $10B+',
  },
  {
    llcName: 'Balloonist LLC',
    company: 'Meta',
    confidence: 'confirmed',
    state: 'DE',
    location: 'Beaver Dam & Menomonie, Wisconsin, USA',
    project: 'Wisconsin Data Center',
    lat: 43.4675,
    lng: -88.8376,
    status: 'proposed',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 0,
    ndaInvolved: false,
    sourceType: 'news',
    notes: '$1B+; pre-development agreements behind closed doors',
  },
  {
    llcName: 'Degas LLC',
    company: 'Meta',
    confidence: 'confirmed',
    state: 'DE',
    location: 'Beaver Dam, Wisconsin, USA',
    project: 'Beaver Dam Data Center',
    lat: 43.4675,
    lng: -88.8376,
    status: 'proposed',
    facilityType: 'hyperscale data center',
    incentivesKnown: false,
    incentiveAmount: 0,
    ndaInvolved: false,
    sourceType: 'news',
    notes: "Council voted 12-0 without mentioning 'data center'",
  },
];

const amazonLlcs: LlcEntry[] = [
  {
    llcName: 'Vadata Inc.',
    company: 'Amazon',
    confidence: 'confirmed',
    state: 'WA',
    location: 'Northern Virginia / Oregon / Ohio (multiple)',
    project: 'Multiple AWS Data Centers',
    lat: 38.9072,
    lng: -77.0369,
    status: 'operating',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 81000000,
    ndaInvolved: false,
    sourceType: 'sec_filing',
    notes: 'OR: $1B+ enterprise zone exemptions; VA: $2.7M tax breaks; OH: $81M sales tax exemption',
  },
  {
    llcName: 'Amazon Data Services Inc.',
    company: 'Amazon',
    confidence: 'confirmed',
    state: 'WA',
    location: 'Virginia / Georgia / Ohio / Indiana / Pennsylvania (multiple)',
    project: 'Multiple AWS Data Centers',
    lat: 38.9072,
    lng: -77.0369,
    status: 'operating',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 180000000,
    ndaInvolved: false,
    sourceType: 'sec_filing',
    notes: 'Sidney OH: 30-year 100% abatement ($180-350M); Hobart IN: 10-year property tax abatement',
  },
  {
    llcName: 'Razor5',
    company: 'Amazon',
    confidence: 'confirmed',
    state: 'IN/DE',
    location: 'New Carlisle, Indiana, USA',
    project: 'Project Rainier Data Center',
    lat: 41.5378,
    lng: -86.5086,
    status: 'approved',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 8280000000,
    ndaInvolved: true,
    sourceType: 'news',
    notes: '$8.28B total incentives; 50% property abatement; 85% personal property abatement for 35 years',
  },
  {
    llcName: 'Hobart Owner LLC',
    company: 'Amazon',
    confidence: 'confirmed',
    state: 'IN',
    location: 'Hobart, Indiana, USA',
    project: 'Hobart Data Center Campus',
    lat: 41.5325,
    lng: -87.2550,
    status: 'approved',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 102000000,
    ndaInvolved: false,
    sourceType: 'news',
    notes: '10-year 100% property tax abatement; 35-year 100% IT equipment exemption; $102M community payments',
  },
  {
    llcName: 'Hobart Devco LLC',
    company: 'Amazon',
    confidence: 'confirmed',
    state: 'IN',
    location: 'Hobart, Indiana, USA',
    project: 'Hobart Campus Development',
    lat: 41.5325,
    lng: -87.2550,
    status: 'approved',
    facilityType: 'hyperscale data center',
    incentivesKnown: false,
    incentiveAmount: 0,
    ndaInvolved: false,
    sourceType: 'news',
    notes: 'Campus development entity for $15B project',
  },
  {
    llcName: 'Elk River Technologies',
    company: 'Amazon',
    confidence: 'confirmed intermediary',
    state: 'MN',
    location: 'Becker, Minnesota, USA',
    project: 'Becker Land Acquisition',
    lat: 45.3969,
    lng: -93.8727,
    status: 'operating',
    facilityType: 'land acquisition intermediary',
    incentivesKnown: false,
    incentiveAmount: 0,
    ndaInvolved: false,
    sourceType: 'news',
    notes: 'Bought 348 acres for $7.7M; flipped to Amazon for $73.5M (nearly 10x markup)',
  },
];

const microsoftLlcs: LlcEntry[] = [
  {
    llcName: 'Franklin Lowell LLC',
    company: 'Microsoft',
    confidence: 'confirmed intermediary',
    state: 'IL/MI',
    location: 'Lowell Township, Michigan, USA',
    project: 'Lowell Township Data Center',
    lat: 42.9367,
    lng: -85.3441,
    status: 'proposed',
    facilityType: 'hyperscale data center',
    incentivesKnown: false,
    incentiveAmount: 0,
    ndaInvolved: true,
    sourceType: 'news',
    notes: 'Rezoning filed under NDA; $500M-$1B investment; Microsoft identity concealed',
  },
  {
    llcName: 'Franklin Partners',
    company: 'Microsoft',
    confidence: 'confirmed intermediary',
    state: 'IL/MI',
    location: 'Multiple Michigan townships, USA',
    project: 'Michigan Data Center Portfolio',
    lat: 42.9367,
    lng: -85.3441,
    status: 'proposed',
    facilityType: 'hyperscale data center',
    incentivesKnown: false,
    incentiveAmount: 0,
    ndaInvolved: true,
    sourceType: 'news',
    notes: 'NDAs signed with 4 communities on Microsoft behalf',
  },
  {
    llcName: 'EdgeConneX',
    company: 'Microsoft',
    confidence: 'confirmed for Microsoft',
    state: 'GA',
    location: 'Union City, Georgia, USA',
    project: 'Project Steamboat Data Center',
    lat: 33.5871,
    lng: -84.5416,
    status: 'approved',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 75000000,
    ndaInvolved: true,
    sourceType: 'news',
    notes: '$75M tax break from Fulton County; $420M bonds',
  },
  {
    llcName: 'Microsoft (direct)',
    company: 'Microsoft',
    confidence: 'confirmed',
    state: 'OH',
    location: 'New Albany, Ohio, USA',
    project: 'New Albany AI Data Center',
    lat: 40.0809,
    lng: -82.7913,
    status: 'operating',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 72500000,
    ndaInvolved: false,
    sourceType: 'news',
    notes: '15-year 100% property tax abatement; $72.5M sales tax exemption',
  },
  {
    llcName: 'Microsoft (direct)',
    company: 'Microsoft',
    confidence: 'confirmed',
    state: 'WI',
    location: 'Mount Pleasant, Wisconsin, USA',
    project: 'Mount Pleasant AI Data Center',
    lat: 42.7261,
    lng: -87.8897,
    status: 'approved',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 0,
    ndaInvolved: false,
    sourceType: 'news',
    notes: '$3.3B AI data center; state sales/use tax exemption; TID from Foxconn era',
  },
  {
    llcName: 'Microsoft (direct)',
    company: 'Microsoft',
    confidence: 'confirmed',
    state: 'WY',
    location: 'Cheyenne, Wyoming, USA',
    project: 'Cheyenne Data Center',
    lat: 41.1400,
    lng: -104.8202,
    status: 'operating',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 0,
    ndaInvolved: false,
    sourceType: 'news',
    notes: 'Wyoming data center sales tax exemption on equipment',
  },
  {
    llcName: 'Microsoft (direct)',
    company: 'Microsoft',
    confidence: 'confirmed',
    state: 'IN',
    location: 'Granger, Indiana, USA',
    project: 'Granger Data Center',
    lat: 41.7370,
    lng: -86.1386,
    status: 'proposed',
    facilityType: 'hyperscale data center',
    incentivesKnown: false,
    incentiveAmount: 0,
    ndaInvolved: false,
    sourceType: 'news',
    notes: 'Pledged NOT to seek property tax abatement (Feb 2026)',
  },
  {
    llcName: 'Microsoft (direct)',
    company: 'Microsoft',
    confidence: 'confirmed',
    state: 'IL',
    location: 'Hoffman Estates, Illinois, USA',
    project: 'Hoffman Estates Data Center',
    lat: 42.0631,
    lng: -88.0800,
    status: 'operating',
    facilityType: 'hyperscale data center',
    incentivesKnown: true,
    incentiveAmount: 38000000,
    ndaInvolved: false,
    sourceType: 'news',
    notes: '$38M sales tax exemption for 20 jobs',
  },
];

export const companyProfiles: CompanyProfile[] = [
  {
    name: 'Google',
    slug: 'google',
    description:
      'Known data center LLCs and shell companies used for land, incentives, and development deals.',
    llcCount: 23,
    llcs: googleLlcs,
  },
  {
    name: 'Meta Platforms, Inc.',
    slug: 'meta',
    description:
      'Meta frequently uses single-purpose LLCs to acquire land, secure incentives, and develop hyperscale data centers before its identity is public.',
    llcCount: 19,
    llcs: metaLlcs,
  },
  {
    name: 'Amazon',
    slug: 'amazon',
    description:
      'Amazon Web Services uses a range of subsidiary entities to secure land, tax incentives, and development agreements across the US.',
    llcCount: 6,
    llcs: amazonLlcs,
  },
  {
    name: 'Microsoft',
    slug: 'microsoft',
    description:
      'Microsoft uses intermediaries and direct subsidiaries to develop hyperscale AI data centers, often under NDAs with local governments.',
    llcCount: 4,
    llcs: microsoftLlcs,
  },
];

export const allLlcs: LlcEntry[] = [
  ...googleLlcs,
  ...metaLlcs,
  ...amazonLlcs,
  ...microsoftLlcs,
];
