// ---------------------------------------------------------------------------
// County-level data for enhanced susceptibility scoring
// Michigan and Virginia priority counties — full 5-digit ZIP lookup
// All other states use STATE_DATA in page.tsx
// ---------------------------------------------------------------------------

/** Maps full 5-digit ZIP code to county name and state abbreviation.
 *  If the county name exists as a key in COUNTY_DATA, enhanced scoring is applied. */
export const ZIP_TO_COUNTY: Record<string, { county: string; state: string }> = {

  // MICHIGAN — Washtenaw County (Ann Arbor area)
  '48103': { county: 'Washtenaw County', state: 'MI' },
  '48104': { county: 'Washtenaw County', state: 'MI' },
  '48105': { county: 'Washtenaw County', state: 'MI' },
  '48106': { county: 'Washtenaw County', state: 'MI' },
  '48107': { county: 'Washtenaw County', state: 'MI' },
  '48108': { county: 'Washtenaw County', state: 'MI' },
  '48109': { county: 'Washtenaw County', state: 'MI' },
  '48113': { county: 'Washtenaw County', state: 'MI' },
  '48115': { county: 'Washtenaw County', state: 'MI' },
  '48118': { county: 'Washtenaw County', state: 'MI' },
  '48130': { county: 'Washtenaw County', state: 'MI' },
  '48137': { county: 'Washtenaw County', state: 'MI' },
  '48158': { county: 'Washtenaw County', state: 'MI' },
  '48160': { county: 'Washtenaw County', state: 'MI' },
  '48167': { county: 'Washtenaw County', state: 'MI' },
  '48168': { county: 'Washtenaw County', state: 'MI' },
  '48176': { county: 'Washtenaw County', state: 'MI' },
  '48178': { county: 'Washtenaw County', state: 'MI' },
  '48189': { county: 'Washtenaw County', state: 'MI' },
  '48197': { county: 'Washtenaw County', state: 'MI' },
  '48198': { county: 'Washtenaw County', state: 'MI' },

  // MICHIGAN — Kent County (Grand Rapids / Lowell Township — Microsoft activity)
  '49301': { county: 'Kent County', state: 'MI' },
  '49302': { county: 'Kent County', state: 'MI' },
  '49303': { county: 'Kent County', state: 'MI' },
  '49305': { county: 'Kent County', state: 'MI' },
  '49306': { county: 'Kent County', state: 'MI' },
  '49315': { county: 'Kent County', state: 'MI' },
  '49316': { county: 'Kent County', state: 'MI' },
  '49318': { county: 'Kent County', state: 'MI' },
  '49319': { county: 'Kent County', state: 'MI' },
  '49321': { county: 'Kent County', state: 'MI' },
  '49325': { county: 'Kent County', state: 'MI' },
  '49326': { county: 'Kent County', state: 'MI' },
  '49330': { county: 'Kent County', state: 'MI' },
  '49331': { county: 'Kent County', state: 'MI' }, // Lowell Township
  '49333': { county: 'Kent County', state: 'MI' },
  '49341': { county: 'Kent County', state: 'MI' },
  '49343': { county: 'Kent County', state: 'MI' },
  '49345': { county: 'Kent County', state: 'MI' },
  '49346': { county: 'Kent County', state: 'MI' },
  '49348': { county: 'Kent County', state: 'MI' },
  '49418': { county: 'Kent County', state: 'MI' },
  '49419': { county: 'Kent County', state: 'MI' },
  '49501': { county: 'Kent County', state: 'MI' },
  '49502': { county: 'Kent County', state: 'MI' },
  '49503': { county: 'Kent County', state: 'MI' },
  '49504': { county: 'Kent County', state: 'MI' },
  '49505': { county: 'Kent County', state: 'MI' },
  '49506': { county: 'Kent County', state: 'MI' },
  '49507': { county: 'Kent County', state: 'MI' },
  '49508': { county: 'Kent County', state: 'MI' },
  '49509': { county: 'Kent County', state: 'MI' },
  '49510': { county: 'Kent County', state: 'MI' },
  '49512': { county: 'Kent County', state: 'MI' },
  '49514': { county: 'Kent County', state: 'MI' },
  '49515': { county: 'Kent County', state: 'MI' },
  '49516': { county: 'Kent County', state: 'MI' },
  '49518': { county: 'Kent County', state: 'MI' },
  '49519': { county: 'Kent County', state: 'MI' },
  '49525': { county: 'Kent County', state: 'MI' },
  '49530': { county: 'Kent County', state: 'MI' },
  '49534': { county: 'Kent County', state: 'MI' },
  '49544': { county: 'Kent County', state: 'MI' },
  '49546': { county: 'Kent County', state: 'MI' },
  '49548': { county: 'Kent County', state: 'MI' },
  '49560': { county: 'Kent County', state: 'MI' },
  '49588': { county: 'Kent County', state: 'MI' },
  '49599': { county: 'Kent County', state: 'MI' },

  // MICHIGAN — Ottawa County (Franklin Partners / Microsoft activity)
  '49401': { county: 'Ottawa County', state: 'MI' },
  '49403': { county: 'Ottawa County', state: 'MI' },
  '49404': { county: 'Ottawa County', state: 'MI' },
  '49408': { county: 'Ottawa County', state: 'MI' },
  '49409': { county: 'Ottawa County', state: 'MI' },
  '49415': { county: 'Ottawa County', state: 'MI' },
  '49417': { county: 'Ottawa County', state: 'MI' },
  '49420': { county: 'Ottawa County', state: 'MI' },
  '49423': { county: 'Ottawa County', state: 'MI' },
  '49424': { county: 'Ottawa County', state: 'MI' },
  '49426': { county: 'Ottawa County', state: 'MI' },
  '49428': { county: 'Ottawa County', state: 'MI' },
  '49429': { county: 'Ottawa County', state: 'MI' },
  '49434': { county: 'Ottawa County', state: 'MI' },
  '49435': { county: 'Ottawa County', state: 'MI' },
  '49437': { county: 'Ottawa County', state: 'MI' },
  '49440': { county: 'Ottawa County', state: 'MI' },
  '49441': { county: 'Ottawa County', state: 'MI' },
  '49442': { county: 'Ottawa County', state: 'MI' },
  '49443': { county: 'Ottawa County', state: 'MI' },
  '49444': { county: 'Ottawa County', state: 'MI' },
  '49445': { county: 'Ottawa County', state: 'MI' },
  '49448': { county: 'Ottawa County', state: 'MI' },
  '49449': { county: 'Ottawa County', state: 'MI' },
  '49451': { county: 'Ottawa County', state: 'MI' },
  '49456': { county: 'Ottawa County', state: 'MI' },
  '49457': { county: 'Ottawa County', state: 'MI' },
  '49460': { county: 'Ottawa County', state: 'MI' },
  '49461': { county: 'Ottawa County', state: 'MI' },
  '49464': { county: 'Ottawa County', state: 'MI' },

  // MICHIGAN — Wayne County (Detroit)
  '48101': { county: 'Wayne County', state: 'MI' },
  '48111': { county: 'Wayne County', state: 'MI' },
  '48120': { county: 'Wayne County', state: 'MI' },
  '48121': { county: 'Wayne County', state: 'MI' },
  '48122': { county: 'Wayne County', state: 'MI' },
  '48123': { county: 'Wayne County', state: 'MI' },
  '48124': { county: 'Wayne County', state: 'MI' },
  '48125': { county: 'Wayne County', state: 'MI' },
  '48126': { county: 'Wayne County', state: 'MI' },
  '48127': { county: 'Wayne County', state: 'MI' },
  '48128': { county: 'Wayne County', state: 'MI' },
  '48134': { county: 'Wayne County', state: 'MI' },
  '48135': { county: 'Wayne County', state: 'MI' },
  '48138': { county: 'Wayne County', state: 'MI' },
  '48141': { county: 'Wayne County', state: 'MI' },
  '48146': { county: 'Wayne County', state: 'MI' },
  '48150': { county: 'Wayne County', state: 'MI' },
  '48151': { county: 'Wayne County', state: 'MI' },
  '48152': { county: 'Wayne County', state: 'MI' },
  '48153': { county: 'Wayne County', state: 'MI' },
  '48154': { county: 'Wayne County', state: 'MI' },
  '48164': { county: 'Wayne County', state: 'MI' },
  '48173': { county: 'Wayne County', state: 'MI' },
  '48174': { county: 'Wayne County', state: 'MI' },
  '48180': { county: 'Wayne County', state: 'MI' },
  '48183': { county: 'Wayne County', state: 'MI' },
  '48184': { county: 'Wayne County', state: 'MI' },
  '48185': { county: 'Wayne County', state: 'MI' },
  '48186': { county: 'Wayne County', state: 'MI' },
  '48187': { county: 'Wayne County', state: 'MI' },
  '48188': { county: 'Wayne County', state: 'MI' },
  '48192': { county: 'Wayne County', state: 'MI' },
  '48193': { county: 'Wayne County', state: 'MI' },
  '48195': { county: 'Wayne County', state: 'MI' },
  '48201': { county: 'Wayne County', state: 'MI' },
  '48202': { county: 'Wayne County', state: 'MI' },
  '48203': { county: 'Wayne County', state: 'MI' },
  '48204': { county: 'Wayne County', state: 'MI' },
  '48205': { county: 'Wayne County', state: 'MI' },
  '48206': { county: 'Wayne County', state: 'MI' },
  '48207': { county: 'Wayne County', state: 'MI' },
  '48208': { county: 'Wayne County', state: 'MI' },
  '48209': { county: 'Wayne County', state: 'MI' },
  '48210': { county: 'Wayne County', state: 'MI' },
  '48211': { county: 'Wayne County', state: 'MI' },
  '48212': { county: 'Wayne County', state: 'MI' },
  '48213': { county: 'Wayne County', state: 'MI' },
  '48214': { county: 'Wayne County', state: 'MI' },
  '48215': { county: 'Wayne County', state: 'MI' },
  '48216': { county: 'Wayne County', state: 'MI' },
  '48217': { county: 'Wayne County', state: 'MI' },
  '48218': { county: 'Wayne County', state: 'MI' },
  '48219': { county: 'Wayne County', state: 'MI' },
  '48220': { county: 'Wayne County', state: 'MI' },
  '48221': { county: 'Wayne County', state: 'MI' },
  '48222': { county: 'Wayne County', state: 'MI' },
  '48223': { county: 'Wayne County', state: 'MI' },
  '48224': { county: 'Wayne County', state: 'MI' },
  '48225': { county: 'Wayne County', state: 'MI' },
  '48226': { county: 'Wayne County', state: 'MI' },
  '48227': { county: 'Wayne County', state: 'MI' },
  '48228': { county: 'Wayne County', state: 'MI' },
  '48229': { county: 'Wayne County', state: 'MI' },
  '48230': { county: 'Wayne County', state: 'MI' },
  '48231': { county: 'Wayne County', state: 'MI' },
  '48232': { county: 'Wayne County', state: 'MI' },
  '48233': { county: 'Wayne County', state: 'MI' },
  '48234': { county: 'Wayne County', state: 'MI' },
  '48235': { county: 'Wayne County', state: 'MI' },
  '48236': { county: 'Wayne County', state: 'MI' },
  '48237': { county: 'Wayne County', state: 'MI' },
  '48238': { county: 'Wayne County', state: 'MI' },
  '48239': { county: 'Wayne County', state: 'MI' },
  '48240': { county: 'Wayne County', state: 'MI' },
  '48242': { county: 'Wayne County', state: 'MI' },
  '48243': { county: 'Wayne County', state: 'MI' },
  '48244': { county: 'Wayne County', state: 'MI' },

  // VIRGINIA — Loudoun County (Data Center Alley — Ashburn, Sterling, Dulles)
  '20105': { county: 'Loudoun County', state: 'VA' },
  '20129': { county: 'Loudoun County', state: 'VA' },
  '20132': { county: 'Loudoun County', state: 'VA' },
  '20135': { county: 'Loudoun County', state: 'VA' },
  '20141': { county: 'Loudoun County', state: 'VA' },
  '20142': { county: 'Loudoun County', state: 'VA' },
  '20147': { county: 'Loudoun County', state: 'VA' },
  '20148': { county: 'Loudoun County', state: 'VA' },
  '20152': { county: 'Loudoun County', state: 'VA' },
  '20158': { county: 'Loudoun County', state: 'VA' },
  '20164': { county: 'Loudoun County', state: 'VA' },
  '20165': { county: 'Loudoun County', state: 'VA' },
  '20166': { county: 'Loudoun County', state: 'VA' },
  '20175': { county: 'Loudoun County', state: 'VA' },
  '20176': { county: 'Loudoun County', state: 'VA' },
  '20180': { county: 'Loudoun County', state: 'VA' },
  '20184': { county: 'Loudoun County', state: 'VA' },
  '20197': { county: 'Loudoun County', state: 'VA' },
  '20198': { county: 'Loudoun County', state: 'VA' },

  // VIRGINIA — Prince William County (Digital Gateway rezoning area)
  '20109': { county: 'Prince William County', state: 'VA' },
  '20110': { county: 'Prince William County', state: 'VA' },
  '20111': { county: 'Prince William County', state: 'VA' },
  '20112': { county: 'Prince William County', state: 'VA' },
  '20136': { county: 'Prince William County', state: 'VA' },
  '20155': { county: 'Prince William County', state: 'VA' },
  '20181': { county: 'Prince William County', state: 'VA' },
  '20182': { county: 'Prince William County', state: 'VA' },
  '20187': { county: 'Prince William County', state: 'VA' },
  '20188': { county: 'Prince William County', state: 'VA' },
  '20192': { county: 'Prince William County', state: 'VA' },
  '22025': { county: 'Prince William County', state: 'VA' },
  '22026': { county: 'Prince William County', state: 'VA' },
  '22125': { county: 'Prince William County', state: 'VA' },
  '22172': { county: 'Prince William County', state: 'VA' },
  '22191': { county: 'Prince William County', state: 'VA' },
  '22192': { county: 'Prince William County', state: 'VA' },
  '22193': { county: 'Prince William County', state: 'VA' },

  // VIRGINIA — Fairfax County (Amazon/AWS Reston, Herndon corridor)
  '20120': { county: 'Fairfax County', state: 'VA' },
  '20121': { county: 'Fairfax County', state: 'VA' },
  '20124': { county: 'Fairfax County', state: 'VA' },
  '20151': { county: 'Fairfax County', state: 'VA' },
  '20153': { county: 'Fairfax County', state: 'VA' },
  '20170': { county: 'Fairfax County', state: 'VA' },
  '20171': { county: 'Fairfax County', state: 'VA' },
  '20190': { county: 'Fairfax County', state: 'VA' },
  '20191': { county: 'Fairfax County', state: 'VA' },
  '20194': { county: 'Fairfax County', state: 'VA' },
  '22003': { county: 'Fairfax County', state: 'VA' },
  '22015': { county: 'Fairfax County', state: 'VA' },
  '22027': { county: 'Fairfax County', state: 'VA' },
  '22030': { county: 'Fairfax County', state: 'VA' },
  '22031': { county: 'Fairfax County', state: 'VA' },
  '22032': { county: 'Fairfax County', state: 'VA' },
  '22033': { county: 'Fairfax County', state: 'VA' },
  '22035': { county: 'Fairfax County', state: 'VA' },
  '22039': { county: 'Fairfax County', state: 'VA' },
  '22041': { county: 'Fairfax County', state: 'VA' },
  '22042': { county: 'Fairfax County', state: 'VA' },
  '22043': { county: 'Fairfax County', state: 'VA' },
  '22044': { county: 'Fairfax County', state: 'VA' },
  '22046': { county: 'Fairfax County', state: 'VA' },
  '22060': { county: 'Fairfax County', state: 'VA' },
  '22066': { county: 'Fairfax County', state: 'VA' },
  '22067': { county: 'Fairfax County', state: 'VA' },
  '22079': { county: 'Fairfax County', state: 'VA' },
  '22101': { county: 'Fairfax County', state: 'VA' },
  '22102': { county: 'Fairfax County', state: 'VA' },
  '22124': { county: 'Fairfax County', state: 'VA' },
  '22150': { county: 'Fairfax County', state: 'VA' },
  '22151': { county: 'Fairfax County', state: 'VA' },
  '22152': { county: 'Fairfax County', state: 'VA' },
  '22153': { county: 'Fairfax County', state: 'VA' },
  '22180': { county: 'Fairfax County', state: 'VA' },
  '22181': { county: 'Fairfax County', state: 'VA' },
  '22182': { county: 'Fairfax County', state: 'VA' },
  '22185': { county: 'Fairfax County', state: 'VA' },
  '22199': { county: 'Fairfax County', state: 'VA' },

  // VIRGINIA — Henrico County (Meta Scout Development LLC)
  '23059': { county: 'Henrico County', state: 'VA' },
  '23060': { county: 'Henrico County', state: 'VA' },
  '23069': { county: 'Henrico County', state: 'VA' },
  '23150': { county: 'Henrico County', state: 'VA' },
  '23222': { county: 'Henrico County', state: 'VA' },
  '23223': { county: 'Henrico County', state: 'VA' },
  '23224': { county: 'Henrico County', state: 'VA' },
  '23225': { county: 'Henrico County', state: 'VA' },
  '23226': { county: 'Henrico County', state: 'VA' },
  '23227': { county: 'Henrico County', state: 'VA' },
  '23228': { county: 'Henrico County', state: 'VA' },
  '23229': { county: 'Henrico County', state: 'VA' },
  '23230': { county: 'Henrico County', state: 'VA' },
  '23231': { county: 'Henrico County', state: 'VA' },
  '23233': { county: 'Henrico County', state: 'VA' },
  '23238': { county: 'Henrico County', state: 'VA' },
  '23250': { county: 'Henrico County', state: 'VA' },
  '23255': { county: 'Henrico County', state: 'VA' },
  '23273': { county: 'Henrico County', state: 'VA' },
};

export interface CountyProfile {
  state: string;
  county: string;
  utilityProvider: string;
  utilityType: 'municipal' | 'iou' | 'coop';
  gridRegion: string;
  waterSystemNotes: string;
  waterStressLevel: 'low' | 'moderate' | 'high';
  taxIncentiveTier: 1 | 2 | 3;
  knownDataCenterActivity: boolean;
  activeIncentivePrograms: string[];
  llcTrackerEntries: string[];
  notes: string;
}

/** Keys are county names only (e.g. 'Kent County').
 *  Must match the `county` field returned by ZIP_TO_COUNTY. */
export const COUNTY_DATA: Record<string, CountyProfile> = {
  // -------------------------------------------------------------------------
  // Michigan
  // -------------------------------------------------------------------------
  'Washtenaw County': {
    state: 'MI',
    county: 'Washtenaw County',
    utilityProvider: 'DTE Energy',
    utilityType: 'iou',
    gridRegion: 'MISO',
    waterSystemNotes: 'Ann Arbor water treatment plant, Huron River watershed, serves approximately 120,000 people',
    waterStressLevel: 'low',
    taxIncentiveTier: 2,
    knownDataCenterActivity: false,
    activeIncentivePrograms: ['Michigan Public Act 23 of 2015 data center sales tax exemption'],
    llcTrackerEntries: [],
    notes:
      'Home to University of Michigan; no confirmed hyperscaler data center activity; university computing infrastructure present but not commercial hyperscale',
  },

  'Kent County': {
    state: 'MI',
    county: 'Kent County',
    utilityProvider: 'Consumers Energy / LBWL',
    utilityType: 'iou',
    gridRegion: 'MISO',
    waterSystemNotes: 'Grand River watershed, moderate system size, municipal supply',
    waterStressLevel: 'low',
    taxIncentiveTier: 2,
    knownDataCenterActivity: true,
    activeIncentivePrograms: [
      'Michigan Public Act 23 of 2015 data center sales tax exemption',
      'MEDC business development grants',
    ],
    llcTrackerEntries: ['Franklin Lowell LLC', 'Franklin Partners'],
    notes:
      'Microsoft data center project via Franklin Partners intermediary; NDAs signed with Lowell Township and 3 other townships; community opposition forced Microsoft to reveal identity January 2026',
  },

  'Ottawa County': {
    state: 'MI',
    county: 'Ottawa County',
    utilityProvider: 'Consumers Energy',
    utilityType: 'iou',
    gridRegion: 'MISO',
    waterSystemNotes: 'Lake Michigan watershed, adequate supply',
    waterStressLevel: 'low',
    taxIncentiveTier: 2,
    knownDataCenterActivity: true,
    activeIncentivePrograms: [
      'Michigan Public Act 23 of 2015',
      'MEDC incentives',
    ],
    llcTrackerEntries: ['Franklin Partners'],
    notes:
      'Franklin Partners active in multiple Ottawa County townships on behalf of Microsoft',
  },

  'Wayne County': {
    state: 'MI',
    county: 'Wayne County',
    utilityProvider: 'DTE Energy',
    utilityType: 'iou',
    gridRegion: 'MISO',
    waterSystemNotes: 'Detroit Water and Sewerage Department, large system, Great Lakes supply',
    waterStressLevel: 'low',
    taxIncentiveTier: 2,
    knownDataCenterActivity: false,
    activeIncentivePrograms: ['Michigan Public Act 23 of 2015'],
    llcTrackerEntries: [],
    notes:
      'No confirmed hyperscaler data center activity; urban density makes large campus development less likely',
  },

  // -------------------------------------------------------------------------
  // Virginia
  // -------------------------------------------------------------------------
  'Loudoun County': {
    state: 'VA',
    county: 'Loudoun County',
    utilityProvider: 'Dominion Energy Virginia',
    utilityType: 'iou',
    gridRegion: 'PJM',
    waterSystemNotes:
      'Loudoun Water authority, large system, Potomac River supply, under strain from massive data center load growth',
    waterStressLevel: 'moderate',
    taxIncentiveTier: 1,
    knownDataCenterActivity: true,
    activeIncentivePrograms: [
      'Virginia data center sales tax exemption VA Code 58.1-609.3',
      'Local machinery and tools tax exemption',
      'Loudoun County data center overlay district',
    ],
    llcTrackerEntries: ['Vadata Inc.', 'Amazon Data Services Inc.', 'Franklin Partners'],
    notes:
      'Data Center Alley — highest density data center market in the world. Over 100 data centers operating. Dominion Energy has flagged grid capacity concerns in published IRP. County assessed $1.9B/year in foregone tax revenue per Good Jobs First.',
  },

  'Prince William County': {
    state: 'VA',
    county: 'Prince William County',
    utilityProvider: 'Dominion Energy Virginia',
    utilityType: 'iou',
    gridRegion: 'PJM',
    waterSystemNotes:
      'Prince William County Service Authority, large system, Occoquan Reservoir supply',
    waterStressLevel: 'moderate',
    taxIncentiveTier: 1,
    knownDataCenterActivity: true,
    activeIncentivePrograms: [
      'Virginia data center sales tax exemption',
      'Prince William Digital Gateway rezoning district',
    ],
    llcTrackerEntries: ['Vadata Inc.'],
    notes:
      'Digital Gateway rezoning approved 2023 after major community opposition and temporary moratorium. 2,100 acres rezoned for data center development. Ongoing litigation from community groups.',
  },

  'Henrico County': {
    state: 'VA',
    county: 'Henrico County',
    utilityProvider: 'Dominion Energy Virginia',
    utilityType: 'iou',
    gridRegion: 'PJM',
    waterSystemNotes: 'Henrico County water authority, large system',
    waterStressLevel: 'low',
    taxIncentiveTier: 1,
    knownDataCenterActivity: true,
    activeIncentivePrograms: [
      'Virginia data center sales tax exemption',
      'Henrico County cut data center tax rate by 88%',
    ],
    llcTrackerEntries: ['Scout Development LLC'],
    notes:
      "Meta's Scout Development LLC operating Project Echo data center. County reduced data center machinery and tools tax rate by 88% to attract development.",
  },

  'Fairfax County': {
    state: 'VA',
    county: 'Fairfax County',
    utilityProvider: 'Dominion Energy Virginia',
    utilityType: 'iou',
    gridRegion: 'PJM',
    waterSystemNotes:
      'Fairfax Water authority, very large system, Potomac and Occoquan supply',
    waterStressLevel: 'low',
    taxIncentiveTier: 1,
    knownDataCenterActivity: true,
    activeIncentivePrograms: [
      'Virginia data center sales tax exemption',
      'Fairfax County local tax incentives',
    ],
    llcTrackerEntries: ['Vadata Inc.', 'Amazon Data Services Inc.'],
    notes:
      'Major Amazon/AWS presence in Reston and Herndon corridors. Some of the highest-value data center real estate in the US.',
  },

  'Arlington County': {
    state: 'VA',
    county: 'Arlington County',
    utilityProvider: 'Dominion Energy Virginia',
    utilityType: 'iou',
    gridRegion: 'PJM',
    waterSystemNotes: 'Arlington County water service, large system, Potomac River supply',
    waterStressLevel: 'low',
    taxIncentiveTier: 1,
    knownDataCenterActivity: false,
    activeIncentivePrograms: ['Virginia data center sales tax exemption'],
    llcTrackerEntries: [],
    notes:
      'Dense urban county adjacent to Washington DC. High land costs and limited industrial land reduce large-campus data center viability, though smaller colocation facilities exist.',
  },
};
